databricks_profile:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: workspace
      schema: multas_analytics
      host: dbc-cb78d452-41af.cloud.databricks.com
      http_path: /sql/1.0/warehouses/1e68f97829e80ece
      token: dapi737d7f1c4d14e581252dec28a7e3e053
