version: 2

sources:
    - name: bronze
    database: workspace
    schema: multas_analytics
    tables: 
        - name: multas_pagas
        - name: multas_vencidas

models:
    - name: "null_municipios"
    description: "verificar municipios nulos"
    columns:
        - name: "id_municipio"
        description: "n identificacao municipio"
        tests:
            - unique
            - not_null