version: 2

sources:
  - name: silver
    database: workspace
    schema: multas_analytics
    tables:
      - name: silver_pagas
      - name: silver_vencidas

models:
  - name: quantity_municipios
    description: "verificar municipios nulos"
    columns:
      - name: qtd_municipios
        description: "quantidades de municipio"
        tests:
          - unique
          - not_null
