version: 2

models:
  - name: quantity_per_vehicle_type
    description: "Resumo de multas por tipo de veículo"
    columns:
      - name: TIPO_VEICULO
        description: "Categoria do veículo"
        tests:
          - not_null
          - unique
      - name: QUANTIDADE_TOTAL
        description: "Total de multas por tipo de veículo"
        tests:
          - not_null