## Refino dos dados

from pyspark.sql.functions import col
from pyspark.sql import SparkSession

def iniciar_sessao():

#TRATAR NULOS



# RESOLVER INCONSISTENCIAS

# TRATAR DUPLICIDADES

# TRATAR ERROS DE FORMATO

# TRATAR ERROS DE CONVERSÃO DE TIPO

# TRATAR ERROS DE CONVERSÃO DE DATA

# CRIAR TABELA INTERMEDIARIA COM ID_MUNICIPIO + MUNICIPIOS RELACIONADOS

# INSERIR SPARK.SQL 

# UTILIZAR SPARKDATAFRAMES

# CRIAR TABELAS GOLD_PAGAS / GOLD_VENCIDAS

